### ISSUE TITLE
Convert demoservice to be an installable Github app

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-webteam/demoservice#19]
The demoservice currently uses webhooks and a Github user with permissions.

Converting this service to a full Github application would simplify setting up new repositories, while simplifying the permission system for how the service fetches metadata about the repository.

It may open possibilities for improved build status reporting inside pull requests.

A consideration to take into account is to make sure that this app is still limited to whitelisted repositoried (ie, not publicly installable)

**Comment by tbille** [comment]
I don't think this is really usefull  at the moment. Closing for now.
