### ISSUE TITLE
Add option for custom environment variables

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-webteam/demoservice#26]
Enable options for injecting environment variables, inheriting and overriding with more specific options.

 - Globally for all projects (ie, ENVIRONMENT=QA)
 - Configured globally per project
 - In the form when starting demos / Read GitHub PR message for certain string

Global environment variables can be configured in the code, possibly from database later on.

Per project variables can be set from a `.run.yml` file. This file has been discussed for the new run script.
```yaml
---
run:
  [...]
demo:
  env:
    ENVIRONMENT: "QA"
```

Per demo variables should be able to be set either through the form manually, or also set when a PR is created. One option is a string in the body, possibly a codeblock such as:
```
DEMO_ENV
ENVIRONMENT: STILL_QA
```

**Comment by tbille** [comment]
We are adding this in the `.env` files which is read by the run script.
