### ISSUE TITLE
Update demos when PRs change

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/demoservice#29]
This should work, based on receiving the `synchonized` event from the `pull_request` webhook.

There have been complaints that it does not work and this needs investigating/fixing.

**Comment by jpmartinspt** [comment]
After some debugging I think the issue might relate with the following:
https://github.community/t5/How-to-use-Git-and-GitHub/Issue-with-fetching-the-latest-PR-commits/td-p/275
