### ISSUE TITLE
Demos don't always stop when PR is merged

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/demoservice#46]
E.g. http://snapcraft.io-canonical-websites-pr-1176.run.demo.haus/ (at the time of writing) (https://github.com/canonical-websites/snapcraft.io/pull/1176):

Shows it's running:

![image](https://user-images.githubusercontent.com/519935/46617313-558eb380-cb14-11e8-8860-6b5f0b2a6fb7.png)

Works fine:

![image](https://user-images.githubusercontent.com/519935/46617330-64756600-cb14-11e8-8ef1-90ae29b49b1c.png)

But the PR is merged, so it should have been removed:

![image](https://user-images.githubusercontent.com/519935/46617363-7eaf4400-cb14-11e8-995c-1d6cf854e66b.png)

We should try to get to the bottom of why.

**Comment by nottrobin** [comment]
It looks like this may be because of webhook timeouts, e.g. for PR #1174:

![image](https://user-images.githubusercontent.com/519935/46618261-f7170480-cb16-11e8-983c-e551e333645f.png)

Or because of another weird webhook problem where "something went wrong":

![image](https://user-images.githubusercontent.com/519935/46618369-36455580-cb17-11e8-92de-76d26b432ce7.png)

So there may be little we can do about it.

**Comment by jpmartinspt** [comment]
I did a little investigation on this and the problem seemed to be undelivered webhooks.
I think we can close this one and implement something like https://github.com/canonical-webteam/demoservice/issues/48 to help reduce the number of unneeded demos.
